apiVersion: {{ template "apiVersion" }}
kind: ClusterSecretStore
metadata:
  labels:
    app: {{ template "ClusterSecretStore.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ template "ClusterSecretStore.name" . }}
{{- if or .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
spec:
  provider:
{{ toYaml .Values.provider | indent 4 }}
